"""Maintain the repository's Markdown documents: check them, and build their indexes.

Five gates run over the tracked Markdown files. The link gate resolves every
in-repo link — relative paths, heading anchors, and `#L<n>` / `#L<n>-L<m>` line
fragments — and fails on a target that does not exist, so a rename, a moved
section, or an edit that shortens a file cannot silently rot a pointer. It
reads the docstrings and comments of the tracked Python under `src/` and
`scripts/` too, where a module links the ADR it implements by a path relative
to itself, so moving the module cannot silently break the link either.
The frontmatter gate requires every document under `docs/` to declare its
`status` and `date`, and requires a `superseded` or `amended` document to name
what replaced or changed it, so a reader can tell a living document from a
finished research note without reading it. The ADR numbering gate requires
every ADR to carry a number no other ADR claims, so a bare "ADR NNNN" in
prose or in a code comment still identifies one document. The index gate
requires the committed ADR index, and the frontmatter and table of each kind
index under `docs/` (research, spikes, reviews, proposals), to be what this
script generates, so a new decision or document cannot be left out of its index and
a changed title, `status` or `date` cannot leave a row behind. The code map
gate requires the code map to link every module and asset the package ships,
and nothing it does not ship, so a new module cannot be left off the map and
a removed one cannot linger on it.

The indexes are generated rather than hand-maintained, because a
hand-maintained table of every document goes stale the moment someone adds
one without touching it. A kind index keeps a hand-written introduction
between its generated frontmatter and its generated table, which marker
comments bound; the ADR index is generated whole. `--write-indexes`
rewrites every index, and so does its older name `--write-adr-index`; the
gate only reports that one needs rewriting. Because the generated parts are a
function of the documents, a rebase conflict confined to them is resolved by
rewriting them. The code map is checked
rather than generated: the concept each module serves and its role are prose
no script can write.

The gate errs towards silence: code and HTML comments are masked before
anything is read out of a document, and everything in a Python file but its
docstrings and comments, because a false failure on a legitimate document is
worse than a missed link. Everything it does report has been resolved against
the tree.
"""

from __future__ import annotations

import argparse
import io
import re
import subprocess
import sys
import tokenize
from collections.abc import Collection, Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from urllib.parse import unquote

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DOCS_DIRECTORY = "docs"
ADR_DIRECTORY = "docs/adr"
# The index beside the ADRs is not itself a decision, so it takes no number and
# declares a document status rather than a decision status.
ADR_INDEX_NAME = "README.md"
ADR_INDEX_PATH = f"{ADR_DIRECTORY}/{ADR_INDEX_NAME}"
ADR_NUMBER_PATTERN = re.compile(r"\A(?P<number>\d{4})-")

INDEX_REGENERATE = "regenerate it with --write-indexes"

# The kind directories under docs/ whose `README.md` lists every document
# beside it. The documents of a subdirectory, such as the spikes' retained
# traces, are not the kind's and are left to their own hand-written index.
KIND_INDEX_DIRECTORIES = (
    "docs/research",
    "docs/spikes",
    "docs/reviews",
    "docs/proposals",
)
KIND_INDEX_NAME = "README.md"
# The lines that bound a kind index's generated table. Everything between them
# is rewritten; the introduction above them and anything below are kept.
KIND_TABLE_START = (
    "<!-- Generated by scripts/maintain_docs.py --write-indexes from each "
    "document's title and frontmatter: edit the introduction above, never the "
    "table. -->"
)
KIND_TABLE_END = "<!-- End of the generated table. -->"

# The Python whose docstrings and comments the link gate reads: the package and
# the repository's scripts. Git's `*` matches across directories.
PYTHON_PATHSPECS = ("src/*.py", "scripts/*.py")

CODE_MAP_PATH = "docs/code-map.md"
# Everything Git tracks here is in the wheel, so this is what the map covers.
PACKAGE_DIRECTORY = "src/dashpot"

# What a `status:` may say. ADRs track a decision's standing; every other
# document declares how it should be read.
ADR_STATUSES = frozenset({"proposed", "accepted", "amended", "superseded"})
DOCUMENT_STATUSES = frozenset({"living", "research", "proposal", "superseded"})

# A status that claims another document changed this one has to name it. Both
# fields hold paths relative to the naming document's own directory, the way
# its prose links are written, and every entry is resolved.
SUCCESSION_FIELDS = {"superseded": "superseded-by", "amended": "amended-by"}

FRONTMATTER_PATTERN = re.compile(r"\A---\n(?P<body>.*?)\n---\n", re.DOTALL)
FRONTMATTER_FIELD_PATTERN = re.compile(
    r"^(?P<name>[A-Za-z][\w-]*):\s*(?P<value>.*?)\s*$"
)
DATE_PATTERN = re.compile(r"\A\d{4}-\d{2}-\d{2}\Z")

# Inline links, and reference definitions but not footnote definitions, whose
# `[^1]: text` body is prose rather than a target.
INLINE_LINK_PATTERN = re.compile(
    r"(?<!\\)!?\[(?:[^\[\]]|\[[^\[\]]*\])*\]\(\s*<?([^()<>\s]+)>?[^()]*\)"
)
REFERENCE_DEFINITION_PATTERN = re.compile(
    r"^ {0,3}\[(?!\^)[^\]]+\]:[^\S\n]*<?(\S+)>?", re.MULTILINE
)

ATX_HEADING_PATTERN = re.compile(
    r"^ {0,3}(?P<hashes>#{1,6})[^\S\n]+(?P<text>.*?)(?:[^\S\n]+#*)?[^\S\n]*$",
    re.MULTILINE,
)
# A setext underline turns the paragraph line above it into a heading.
SETEXT_UNDERLINE_PATTERN = re.compile(r"^ {0,3}(?:=+|-+)[^\S\n]*$")
# An explicit anchor a document places by hand, on any element that carries one.
HTML_ANCHOR_PATTERN = re.compile(
    r"<[A-Za-z][^>]*?\s(?:name|id)\s*=\s*[\"']([^\"']+)[\"']", re.IGNORECASE
)

FENCE_PATTERN = re.compile(r"^ {0,3}(?P<fence>`{3,}|~{3,})(?P<info>.*)$")
INDENTED_CODE_PATTERN = re.compile(r"^(?: {4}|\t)")
LIST_ITEM_PATTERN = re.compile(r"^ *(?:[-*+]|\d+[.)])[^\S\n]")
BLANK_PATTERN = re.compile(r"^[^\S\n]*$")
# Backtick runs delimit an inline code span, within one line; the closing run
# matches in length. An HTML comment that opens a line is a block and may run
# across blank lines; one inside a paragraph ends with it, at a blank line.
# Whichever opens first wins, so a `<!--` inside a span opens no comment, and a
# backtick inside a comment opens no span.
INLINE_MASK_PATTERN = re.compile(
    r"(?P<comment>^ {0,3}<!--.*?-->|<!--(?:(?!\n[^\S\n]*\n).)*?-->)"
    r"|(?<!`)(?P<ticks>`+)(?!`)[^\n]*?(?<!`)(?P=ticks)(?!`)",
    re.DOTALL | re.MULTILINE,
)

# Tokens that neither belong to a statement nor end one: a Python statement is
# a docstring when what remains of it is one string literal.
IGNORED_TOKEN_TYPES = frozenset(
    {
        tokenize.COMMENT,
        tokenize.NL,
        tokenize.INDENT,
        tokenize.DEDENT,
        tokenize.ENCODING,
    }
)

EXTERNAL_SCHEMES = ("http://", "https://", "mailto:", "ftp://", "tel:")

# GitHub's blob-view line fragment (`#L12`, `#L12-L20`) addresses a file's
# lines rather than a heading, so it is checked against the file's length.
LINE_FRAGMENT_PATTERN = re.compile(r"\AL(?P<start>\d+)(?:-L(?P<end>\d+))?\Z")


@dataclass(frozen=True, slots=True)
class Problem:
    """One failure a gate found, addressed to a line of a document."""

    path: str
    line: int
    message: str

    def render(self) -> str:
        """Render the problem as one `path:line: message` line."""
        return f"{self.path}:{self.line}: {self.message}"


def tracked_files(*pathspecs: str) -> list[Path]:
    """List the repository's tracked files that match any of the pathspecs."""
    completed = subprocess.run(
        ["git", "ls-files", "-z", "--", *pathspecs],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return [PROJECT_ROOT / name for name in completed.stdout.split("\0") if name]


def tracked_markdown_files() -> list[Path]:
    """List the repository's tracked Markdown files."""
    return tracked_files("*.md")


def tracked_python_files() -> list[Path]:
    """List the tracked Python whose docstrings and comments the link gate reads."""
    return tracked_files(*PYTHON_PATHSPECS)


def mask_code(text: str, *, spans: bool = True) -> str:
    """Blank every code block and HTML comment, and by default every code span, character for character.

    The result is the same length as the input, so an offset into it is an
    offset into the document and the reported line numbers stay true. Heading
    text keeps its spans, because a slug is built from what a span renders as.
    """
    return mask_inline(mask_blocks(text), spans=spans)


def mask_blocks(text: str) -> str:
    """Blank every fenced and indented code block, character for character."""
    lines = text.split("\n")
    masked: list[str] = []
    fence: str | None = None
    indented = False
    for index, line in enumerate(lines):
        blank = BLANK_PATTERN.match(line) is not None
        match = FENCE_PATTERN.match(line)
        if fence is not None:
            # Only a bare run of the same character, at least as long, closes it.
            if (
                match is not None
                and match.group("fence").startswith(fence[0])
                and len(match.group("fence")) >= len(fence)
                and not match.group("info").strip()
            ):
                fence = None
            masked.append(" " * len(line))
            continue
        if match is not None:
            fence = str(match.group("fence"))
            masked.append(" " * len(line))
            continue
        if indented and (blank or INDENTED_CODE_PATTERN.match(line)):
            masked.append(" " * len(line))
            continue
        indented = False
        # An indented block opens only after a blank line, and never where a
        # list is running: a wrapped list item is prose, and its links count.
        if INDENTED_CODE_PATTERN.match(line) and opens_indented_code(lines, index):
            indented = True
            masked.append(" " * len(line))
            continue
        masked.append(line)
    return "\n".join(masked)


def mask_inline(text: str, *, spans: bool = True) -> str:
    """Blank every HTML comment, and by default every code span, character for character.

    A comment is blanked whether or not spans are, and a span is still found
    when it is kept, so a `<!--` it holds never opens a comment. Only a closed
    comment is blanked: an unclosed `<!--` is left as the text it may be.
    Newlines are kept, so offsets and reported line numbers stay true.
    """

    def blank(match: re.Match[str]) -> str:
        if match.group("comment") is None and not spans:
            return match.group(0)
        return re.sub(r"[^\n]", " ", match.group(0))

    return INLINE_MASK_PATTERN.sub(blank, text)


def mask_python_code(text: str) -> str:
    """Blank everything in Python source but its comments and docstrings, character for character.

    A docstring here is any statement that is one string literal and nothing
    else, so the attribute docstrings PEP 257 names count as well as a
    module's, class's or function's. A string inside a larger expression, every
    f-string, and implicitly concatenated literals, whose quotes would fall
    inside their text, are code and blanked with the rest. Newlines are kept,
    so offsets and reported line numbers stay true.

    Raises `SyntaxError` or `tokenize.TokenError` for source Python cannot
    tokenize.
    """
    starts = [0, *(match.end() for match in re.finditer(r"\n", text))]

    def offset(position: tuple[int, int]) -> int:
        row, column = position
        return starts[row - 1] + column

    kept: list[tuple[int, int]] = []
    statement: list[tokenize.TokenInfo] = []
    for token in tokenize.generate_tokens(io.StringIO(text).readline):
        if token.type == tokenize.COMMENT:
            kept.append((offset(token.start), offset(token.end)))
        elif token.type in (tokenize.NEWLINE, tokenize.ENDMARKER):
            if len(statement) == 1 and statement[0].type == tokenize.STRING:
                kept.append((offset(statement[0].start), offset(statement[0].end)))
            statement = []
        elif token.type not in IGNORED_TOKEN_TYPES:
            statement.append(token)
    prose = [character if character == "\n" else " " for character in text]
    for start, end in kept:
        prose[start:end] = text[start:end]
    return "".join(prose)


def mask_for_links(path: Path, text: str) -> str:
    """Blank everything in a file the link gate must not read links out of."""
    if is_python(path):
        return mask_inline(mask_python_code(text))
    return mask_code(text)


def is_python(path: Path) -> bool:
    """Report whether a file is Python, whose docstrings and comments are read for links."""
    return path.suffix == ".py"


def opens_indented_code(lines: Sequence[str], index: int) -> bool:
    """Report whether an indented line starts a code block rather than prose."""
    for previous in reversed(lines[:index]):
        if BLANK_PATTERN.match(previous) is not None:
            continue
        # Prose that a list introduced continues into its indented lines.
        return LIST_ITEM_PATTERN.match(
            previous
        ) is None and not INDENTED_CODE_PATTERN.match(previous)
    return False


def slugify_heading(text: str) -> str:
    """Slugify a heading the way GitHub anchors it."""
    without_links = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    without_code = without_links.replace("`", "")
    # `*` never appears inside a word; `_` does, and GitHub keeps an intraword
    # one, so only a delimiter run at a word boundary is emphasis.
    without_emphasis = re.sub(r"\*{1,3}(?=\S)(.*?)(?<=\S)\*{1,3}", r"\1", without_code)
    without_emphasis = re.sub(
        r"(?<!\w)_{1,3}(?=\S)(.*?)(?<=\S)_{1,3}(?!\w)", r"\1", without_emphasis
    )
    lowered = without_emphasis.strip().lower()
    kept = re.sub(r"[^\w\- ]", "", lowered)
    return kept.replace(" ", "-")


def mask_frontmatter(text: str) -> str:
    """Blank a document's leading frontmatter, character for character.

    GitHub renders frontmatter as a table rather than as Markdown, and its
    closing `---` would otherwise underline the last field as a setext heading.
    Every newline is kept, so offsets and reported line numbers stay true.
    """
    match = FRONTMATTER_PATTERN.match(text)
    if match is None:
        return text
    return re.sub(r"[^\n]", " ", match.group(0)) + text[match.end() :]


def heading_source(text: str) -> str:
    """Blank a document's frontmatter and code blocks, leaving what its headings are read from."""
    return mask_code(mask_frontmatter(text), spans=False)


def iter_headings(masked: str) -> Iterable[tuple[int, str]]:
    """Yield the level and text of every ATX and setext heading, in document order."""
    lines = masked.split("\n")
    for index, line in enumerate(lines):
        atx = ATX_HEADING_PATTERN.match(line)
        if atx is not None:
            yield len(atx.group("hashes")), str(atx.group("text"))
            continue
        if index == 0:
            continue
        underline = SETEXT_UNDERLINE_PATTERN.match(line)
        if underline is None:
            continue
        above = lines[index - 1]
        if (
            BLANK_PATTERN.match(above) is None
            and ATX_HEADING_PATTERN.match(above) is None
        ):
            yield (1 if "=" in underline.group(0) else 2), above.strip()


def document_anchors(text: str) -> set[str]:
    """Collect the anchors a document's headings and explicit ids define."""
    masked = heading_source(text)
    anchors: set[str] = set()
    seen: dict[str, int] = {}
    for _, heading in iter_headings(masked):
        slug = slugify_heading(heading)
        if not slug:
            continue
        count = seen.get(slug, 0)
        seen[slug] = count + 1
        anchors.add(slug if count == 0 else f"{slug}-{count}")
    anchors.update(match.group(1) for match in HTML_ANCHOR_PATTERN.finditer(masked))
    return anchors


def line_of(text: str, offset: int) -> int:
    """Report the 1-indexed line an offset falls on."""
    return text.count("\n", 0, offset) + 1


def iter_link_targets(masked: str) -> Iterable[tuple[str, int]]:
    """Yield every link target in a document with its character offset."""
    for pattern in (INLINE_LINK_PATTERN, REFERENCE_DEFINITION_PATTERN):
        for match in pattern.finditer(masked):
            yield match.group(1), match.start(1)


def resolve_in_repository(path: Path, location: str) -> Path | None:
    """Resolve a link's path half, or report that it leaves the repository."""
    resolved = (path.parent / location).resolve()
    if resolved != PROJECT_ROOT and PROJECT_ROOT not in resolved.parents:
        return None
    return resolved


def line_fragment_problem(target: Path, fragment: re.Match[str]) -> str | None:
    """Explain why a `#L` fragment names lines the file does not have."""
    if not target.is_file():
        return None
    start = int(fragment.group("start"))
    end = int(fragment.group("end") or start)
    if start < 1 or end < start:
        return f"#{fragment.group(0)} is not a line range"
    count = len(target.read_bytes().splitlines())
    if end > count:
        return f"#{fragment.group(0)} is beyond its {count} lines"
    return None


def check_links(paths: Sequence[Path]) -> list[Problem]:
    """Resolve every in-repo link and report the ones that lead nowhere."""
    anchors_by_path: dict[Path, set[str]] = {}

    def anchors_for(target: Path) -> set[str]:
        if target not in anchors_by_path:
            anchors_by_path[target] = document_anchors(
                target.read_text(encoding="utf-8")
            )
        return anchors_by_path[target]

    problems: list[Problem] = []
    for path in paths:
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        try:
            source = mask_for_links(path, text)
        except (SyntaxError, tokenize.TokenError) as error:
            problems.append(
                Problem(
                    relative, 1, f"cannot read its docstrings and comments: {error}"
                )
            )
            continue
        for target, offset in iter_link_targets(source):
            if target.startswith(EXTERNAL_SCHEMES) or target.startswith("//"):
                continue
            line = line_of(text, offset)
            location, _, raw_anchor = target.partition("#")
            anchor = unquote(raw_anchor)
            fragment = LINE_FRAGMENT_PATTERN.match(anchor)
            if fragment is not None:
                anchor = ""
            if not location:
                # Python has no headings for an anchor to name.
                if anchor and not is_python(path) and anchor not in anchors_for(path):
                    problems.append(
                        Problem(relative, line, f"no heading anchors #{anchor}")
                    )
                continue
            location = unquote(location.partition("?")[0])
            resolved = resolve_in_repository(path, location)
            if resolved is None:
                problems.append(
                    Problem(relative, line, f"link leaves the repository: {location}")
                )
                continue
            if not resolved.exists():
                problems.append(
                    Problem(relative, line, f"link target is missing: {location}")
                )
                continue
            if fragment is not None:
                explanation = line_fragment_problem(resolved, fragment)
                if explanation is not None:
                    problems.append(
                        Problem(relative, line, f"{location} {explanation}")
                    )
                continue
            if (
                anchor
                and resolved.suffix == ".md"
                and anchor not in anchors_for(resolved)
            ):
                problems.append(
                    Problem(
                        relative, line, f"{location} has no heading anchoring #{anchor}"
                    )
                )
    return problems


def parse_frontmatter(text: str) -> dict[str, str] | None:
    """Read a document's leading YAML frontmatter as flat string fields."""
    match = FRONTMATTER_PATTERN.match(text)
    if match is None:
        return None
    fields: dict[str, str] = {}
    for line in match.group("body").split("\n"):
        field = FRONTMATTER_FIELD_PATTERN.match(line)
        if field is not None:
            fields[field.group("name")] = field.group("value").strip("\"'")
    return fields


def check_succession(
    path: Path, relative: str, status: str, fields: dict[str, str]
) -> list[Problem]:
    """Require a changed document to name what changed it, and resolve each name."""
    field = SUCCESSION_FIELDS.get(status)
    if field is None:
        return []
    named = fields.get(field, "")
    if not named.strip():
        return [Problem(relative, 2, f"status {status!r} declares no {field}")]
    problems: list[Problem] = []
    for entry in (item.strip() for item in named.split(",")):
        if not entry:
            continue
        resolved = resolve_in_repository(path, entry)
        if resolved is None or not resolved.exists():
            problems.append(
                Problem(relative, 2, f"{field} names a missing document: {entry}")
            )
    return problems


def check_frontmatter(paths: Sequence[Path]) -> list[Problem]:
    """Require a declared `status` and `date` on every document under docs/."""
    problems: list[Problem] = []
    for path in paths:
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        if not relative.startswith(f"{DOCS_DIRECTORY}/"):
            continue
        allowed = ADR_STATUSES if is_adr(path) else DOCUMENT_STATUSES
        fields = parse_frontmatter(path.read_text(encoding="utf-8"))
        if fields is None:
            problems.append(
                Problem(relative, 1, "no frontmatter; expected a status and a date")
            )
            continue
        status = fields.get("status")
        if status is None:
            problems.append(Problem(relative, 2, "frontmatter declares no status"))
        elif status not in allowed:
            expected = ", ".join(sorted(allowed))
            problems.append(
                Problem(relative, 2, f"status {status!r} is not one of: {expected}")
            )
        else:
            problems.extend(check_succession(path, relative, status, fields))
        date = fields.get("date")
        if date is None:
            problems.append(Problem(relative, 2, "frontmatter declares no date"))
        elif not DATE_PATTERN.match(date):
            problems.append(Problem(relative, 2, f"date {date!r} is not YYYY-MM-DD"))
    return problems


def check_adr_numbers(paths: Sequence[Path]) -> list[Problem]:
    """Require every ADR to carry a number no other ADR claims.

    A number identifies a decision where no link resolves it — running prose
    and code comments say "ADR NNNN" and nothing else — so two ADRs sharing
    one leave every bare reference naming neither. Uniqueness is a property of
    the directory rather than of a document, so the caller passes the whole
    tracked set; a narrowed selection cannot answer it.
    """
    problems: list[Problem] = []
    by_number: dict[str, list[str]] = {}
    for path in sorted(paths):
        if not is_adr(path):
            continue
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        match = ADR_NUMBER_PATTERN.match(path.name)
        if match is None:
            problems.append(
                Problem(relative, 1, "filename declares no four-digit ADR number")
            )
            continue
        by_number.setdefault(match.group("number"), []).append(relative)
    for number, claimants in sorted(by_number.items()):
        if len(claimants) < 2:
            continue
        for relative in claimants:
            others = ", ".join(other for other in claimants if other != relative)
            problems.append(
                Problem(relative, 1, f"ADR number {number} is also taken by {others}")
            )
    return problems


def is_adr(path: Path) -> bool:
    """Report whether a path is an ADR rather than the index beside them."""
    relative = path.relative_to(PROJECT_ROOT).as_posix()
    return relative.startswith(f"{ADR_DIRECTORY}/") and path.name != ADR_INDEX_NAME


def escape_table_cell(text: str) -> str:
    """Escape what would otherwise end a Markdown table cell.

    Every cell holding text read out of an ADR is escaped, whether or not
    another gate happens to constrain that field today, so a new column needs
    no reasoning about which values are already safe.
    """
    return text.replace("|", "\\|")


@dataclass(frozen=True, slots=True)
class AdrEntry:
    """One ADR as the index lists it."""

    number: str
    title: str
    status: str
    date: str
    filename: str
    resolved_by: tuple[str, ...]


def document_title(text: str) -> str:
    """Read a document's title from its first level-one heading."""
    for level, heading in iter_headings(heading_source(text)):
        if level == 1:
            return heading.strip()
    return ""


def collect_adr_entries(paths: Sequence[Path]) -> list[AdrEntry]:
    """Describe every ADR the index lists, by number."""
    entries: list[AdrEntry] = []
    for path in paths:
        if not is_adr(path):
            continue
        match = ADR_NUMBER_PATTERN.match(path.name)
        if match is None:
            continue
        text = path.read_text(encoding="utf-8")
        fields = parse_frontmatter(text) or {}
        status = fields.get("status", "")
        named = fields.get(SUCCESSION_FIELDS.get(status, ""), "")
        entries.append(
            AdrEntry(
                number=match.group("number"),
                title=document_title(text),
                status=status,
                date=fields.get("date", ""),
                filename=path.name,
                resolved_by=tuple(
                    entry.strip() for entry in named.split(",") if entry.strip()
                ),
            )
        )
    return sorted(entries, key=lambda entry: entry.number)


def render_adr_link(target: str) -> str:
    """Render a link to an ADR, labelled by its number where it has one."""
    match = ADR_NUMBER_PATTERN.match(Path(target).name)
    label = str(match.group("number")) if match is not None else target
    return f"[{escape_table_cell(label)}]({target})"


def render_adr_index(paths: Sequence[Path]) -> str:
    """Render the ADR index from the ADRs themselves.

    The `date:` is the newest ADR's own date rather than the day the index was
    written, so the output is a function of its inputs: the gate can compare
    the committed file whole, and the date moves only when a decision does.
    Comparing the dates as strings is chronological because the frontmatter
    gate requires every one of them to be `YYYY-MM-DD`.
    """
    entries = collect_adr_entries(paths)
    date = max((entry.date for entry in entries), default="")
    lines = [
        "---",
        "status: living",
        f"date: {date}",
        "---",
        "",
        "# Architecture decision records",
        "",
        "Every architectural decision, by number. An `amended` ADR still holds,",
        "with the change recorded in its own Consequences; a `superseded` one no",
        "longer describes the code.",
        "",
        "This index is generated. Run",
        f"`uv run python scripts/{Path(__file__).name} --write-indexes` after",
        "adding or changing an ADR; the documentation gate fails while it is out",
        "of date.",
        "",
        "| ADR | Decision | Status | Resolved by |",
        "| --- | --- | --- | --- |",
    ]
    for entry in entries:
        resolved = (
            ", ".join(render_adr_link(target) for target in entry.resolved_by) or "—"
        )
        lines.append(
            f"| {entry.number} | [{escape_table_cell(entry.title)}]({entry.filename}) "
            f"| {escape_table_cell(entry.status)} | {resolved} |"
        )
    return "\n".join(lines) + "\n"


def check_adr_index(paths: Sequence[Path]) -> list[Problem]:
    """Require the committed ADR index to be the one this script generates.

    A generated index cannot go stale silently, but only if something notices
    that it was not regenerated; that is what this gate is for. An ADR the
    generator cannot title is reported here rather than rendered as an empty
    link, which would satisfy the comparison while saying nothing.
    """
    untitled = untitled_problems(
        ADR_DIRECTORY, collect_adr_entries(paths), "the ADR index"
    )
    if untitled:
        return untitled
    path = PROJECT_ROOT / ADR_INDEX_PATH
    if not path.is_file():
        return [
            Problem(ADR_INDEX_PATH, 1, f"the ADR index is missing; {INDEX_REGENERATE}")
        ]
    if path.read_text(encoding="utf-8") != render_adr_index(paths):
        return [
            Problem(
                ADR_INDEX_PATH,
                1,
                f"the ADR index is out of date; {INDEX_REGENERATE}",
            )
        ]
    return []


def untitled_problems(
    directory: str, entries: Iterable[AdrEntry | KindEntry], index: str
) -> list[Problem]:
    """Report each document an index cannot title, for want of a level-one heading.

    Such a document is reported rather than rendered as an empty link, which
    would satisfy the comparison while telling a reader nothing.
    """
    return [
        Problem(
            f"{directory}/{entry.filename}",
            1,
            f"declares no level-one heading, so {index} cannot title it",
        )
        for entry in entries
        if not entry.title
    ]


@dataclass(frozen=True, slots=True)
class KindEntry:
    """One document as its kind index lists it."""

    title: str
    status: str
    date: str
    filename: str


def kind_documents(paths: Sequence[Path], directory: str) -> list[Path]:
    """Select the documents a kind index lists: those directly in its directory, itself aside."""
    parent = PROJECT_ROOT / directory
    return [
        path
        for path in paths
        if path.parent == parent
        and path.suffix == ".md"
        and path.name != KIND_INDEX_NAME
    ]


def collect_kind_entries(paths: Sequence[Path], directory: str) -> list[KindEntry]:
    """Describe every document a kind index lists, newest first.

    Documents of one date are listed by filename, which a retitle leaves
    alone, so the order is a function of the documents.
    """
    entries: list[KindEntry] = []
    for path in kind_documents(paths, directory):
        text = path.read_text(encoding="utf-8")
        fields = parse_frontmatter(text) or {}
        entries.append(
            KindEntry(
                title=document_title(text),
                status=fields.get("status", ""),
                date=fields.get("date", ""),
                filename=path.name,
            )
        )
    by_filename = sorted(entries, key=lambda entry: entry.filename)
    # A reversed sort keeps its stability, so one date stays in filename order.
    return sorted(by_filename, key=lambda entry: entry.date, reverse=True)


def kind_table_bounds(text: str) -> tuple[int, int] | None:
    """Find a kind index's generated table, from its opening marker to its closing one.

    Only one opening marker followed by one closing marker, each on a line of
    its own, bounds a table: anything else leaves no telling which text is
    generated.
    """
    starts = list(
        re.finditer(
            rf"^{re.escape(KIND_TABLE_START)}[^\S\n]*$", text, flags=re.MULTILINE
        )
    )
    ends = list(
        re.finditer(rf"^{re.escape(KIND_TABLE_END)}[^\S\n]*$", text, flags=re.MULTILINE)
    )
    if len(starts) != 1 or len(ends) != 1 or ends[0].start() < starts[0].end():
        return None
    return starts[0].start(), ends[0].end()


def render_kind_index(entries: Sequence[KindEntry], committed: str) -> str | None:
    """Render a kind index from its documents around its committed introduction.

    The frontmatter and the table between the markers are generated, and the
    frontmatter's `date:` is the newest document's, as the ADR index's is, so
    both are a function of the documents. The introduction between the
    frontmatter and the opening marker, and anything after the closing one,
    are kept as committed, so a rebase conflict confined to the generated
    parts is resolved by rendering again. Returns `None` when the committed
    index marks no table to generate.
    """
    bounds = kind_table_bounds(committed)
    if bounds is None:
        return None
    start, end = bounds
    frontmatter = FRONTMATTER_PATTERN.match(committed)
    introduction = (
        frontmatter.end()
        if frontmatter is not None and frontmatter.end() <= start
        else 0
    )
    date = max((entry.date for entry in entries), default="")
    lines = [
        KIND_TABLE_START,
        "",
        "| Document | Status | Date |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| [{escape_table_cell(entry.title)}]({entry.filename}) "
        f"| {escape_table_cell(entry.status)} | {escape_table_cell(entry.date)} |"
        for entry in entries
    )
    lines.extend(["", KIND_TABLE_END])
    return (
        f"---\nstatus: living\ndate: {date}\n---\n"
        + committed[introduction:start]
        + "\n".join(lines)
        + committed[end:]
    )


def regenerate_kind_index(
    directory: str, entries: Sequence[KindEntry]
) -> str | Problem | None:
    """Render a kind index's next contents, or the problem that prevents it.

    `None` means there is nothing to index: neither an index nor a document
    for one to list.
    """
    path = PROJECT_ROOT / directory / KIND_INDEX_NAME
    relative = f"{directory}/{KIND_INDEX_NAME}"
    if not path.is_file():
        if not entries:
            return None
        return Problem(
            relative,
            1,
            "the kind index is missing; write its introduction above the "
            f"generated table's marker comments, then {INDEX_REGENERATE}",
        )
    rendered = render_kind_index(entries, path.read_text(encoding="utf-8"))
    if rendered is None:
        return Problem(
            relative,
            1,
            "marks no generated table; put the opening and closing marker "
            "comments every kind index carries on lines of their own below "
            f"the introduction, then {INDEX_REGENERATE}",
        )
    return rendered


def check_kind_indexes(paths: Sequence[Path]) -> list[Problem]:
    """Require each kind index's frontmatter and table to be the ones this script generates.

    As for the ADR index, a document the generator cannot title is reported
    rather than rendered as an empty link.
    """
    problems: list[Problem] = []
    for directory in KIND_INDEX_DIRECTORIES:
        entries = collect_kind_entries(paths, directory)
        untitled = untitled_problems(directory, entries, "its kind index")
        if untitled:
            problems.extend(untitled)
            continue
        outcome = regenerate_kind_index(directory, entries)
        if outcome is None:
            continue
        if isinstance(outcome, Problem):
            problems.append(outcome)
            continue
        path = PROJECT_ROOT / directory / KIND_INDEX_NAME
        if path.read_text(encoding="utf-8") != outcome:
            problems.append(
                Problem(
                    f"{directory}/{KIND_INDEX_NAME}",
                    1,
                    f"the kind index is out of date; {INDEX_REGENERATE}",
                )
            )
    return problems


def write_indexes(tracked: Sequence[Path]) -> list[Problem]:
    """Rewrite every generated index, reporting each one that cannot be rewritten.

    An index with a document it cannot title is left as it is rather than
    written with an empty link, which the gate would then fail.
    """
    written: dict[str, str] = {}
    problems = untitled_problems(
        ADR_DIRECTORY, collect_adr_entries(tracked), "the ADR index"
    )
    if not problems:
        written[ADR_INDEX_PATH] = render_adr_index(tracked)
    for directory in KIND_INDEX_DIRECTORIES:
        entries = collect_kind_entries(tracked, directory)
        untitled = untitled_problems(directory, entries, "its kind index")
        if untitled:
            problems.extend(untitled)
            continue
        outcome = regenerate_kind_index(directory, entries)
        if isinstance(outcome, Problem):
            problems.append(outcome)
        elif outcome is not None:
            written[f"{directory}/{KIND_INDEX_NAME}"] = outcome
    for relative, text in written.items():
        (PROJECT_ROOT / relative).write_text(text, encoding="utf-8")
        print(f"wrote {relative}")
    return problems


def tracked_package_files() -> list[str]:
    """List the files the package ships, as repository-relative paths."""
    completed = subprocess.run(
        ["git", "ls-files", "-z", "--", PACKAGE_DIRECTORY],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return [name for name in completed.stdout.split("\0") if name]


def code_map_links(text: str, path: Path) -> dict[str, int]:
    """Map each package path the code map links, relative to the package, to its first line."""
    package = PROJECT_ROOT / PACKAGE_DIRECTORY
    linked: dict[str, int] = {}
    for target, offset in iter_link_targets(mask_code(text)):
        if target.startswith(EXTERNAL_SCHEMES) or target.startswith("//"):
            continue
        location = unquote(target.partition("#")[0].partition("?")[0])
        if not location:
            continue
        resolved = resolve_in_repository(path, location)
        if resolved is None or package not in resolved.parents:
            continue
        linked.setdefault(
            resolved.relative_to(package).as_posix(), line_of(text, offset)
        )
    return linked


def needs_listing(name: str) -> bool:
    """Report whether the code map must list a shipped file at all.

    A package initializer with nothing in it holds no code to find, so only
    one with any content, such as a seam it exports, is listed.
    """
    if PurePosixPath(name).name != "__init__.py":
        return True
    module = PROJECT_ROOT / PACKAGE_DIRECTORY / name
    return not module.is_file() or bool(module.read_text(encoding="utf-8").strip())


def is_listed(name: str, links: Collection[str]) -> bool:
    """Report whether the code map's links cover one shipped file.

    A Python module is listed only by its own path, so a link to its package
    never stands in for it. An asset may be listed by a directory holding it,
    as a bundled skill is by its own directory.
    """
    if name in links:
        return True
    if PurePosixPath(name).suffix == ".py":
        return False
    return any(parent.as_posix() in links for parent in PurePosixPath(name).parents)


def check_code_map(shipped: Sequence[str]) -> list[Problem]:
    """Require the code map to list every shipped module and asset, and nothing else.

    `shipped` holds repository-relative paths, as `git ls-files` prints them.
    A link to a file or directory the package does not ship is reported at
    its line; a shipped file the map leaves out is reported against the map.
    """
    path = PROJECT_ROOT / CODE_MAP_PATH
    if not path.is_file():
        return [Problem(CODE_MAP_PATH, 1, "the code map is missing")]
    text = path.read_text(encoding="utf-8")
    linked = code_map_links(text, path)
    files = {
        PurePosixPath(name).relative_to(PACKAGE_DIRECTORY).as_posix()
        for name in shipped
    }
    directories = {
        parent.as_posix()
        for name in files
        for parent in PurePosixPath(name).parents
        if parent != PurePosixPath(".")
    }
    problems = [
        Problem(
            CODE_MAP_PATH,
            line,
            f"links {PACKAGE_DIRECTORY}/{name}, which the package does not ship",
        )
        for name, line in sorted(linked.items())
        if name not in files and name not in directories
    ]
    problems.extend(
        Problem(
            CODE_MAP_PATH,
            1,
            f"does not list {PACKAGE_DIRECTORY}/{name}; "
            "add it under the concept it serves",
        )
        for name in sorted(files)
        if needs_listing(name) and not is_listed(name, linked.keys())
    )
    return problems


def select(
    tracked: Sequence[Path], names: Sequence[str]
) -> tuple[list[Path], list[str]]:
    """Narrow the tracked files to the named ones, reporting any it does not track."""
    by_resolved = {path.resolve(): path for path in tracked}
    selected: list[Path] = []
    unknown: list[str] = []
    for name in names:
        path = by_resolved.get(Path(name).resolve())
        if path is None:
            unknown.append(name)
        else:
            selected.append(path)
    return selected, unknown


def main(argv: Sequence[str] | None = None) -> int:
    """Run the documentation gates, or rewrite every generated index and stop."""
    parser = argparse.ArgumentParser(
        description=(
            "Check tracked Markdown documents and the links in tracked Python's "
            "docstrings and comments; build the ADR index and the docs/ kind "
            "indexes."
        )
    )
    parser.add_argument(
        "paths", nargs="*", help="files to check; default is every tracked one"
    )
    # The older name stays, and rewrites every index too, so an instruction
    # written before the kind indexes were generated still resolves a rebase
    # conflict in any of them.
    parser.add_argument(
        "--write-indexes",
        "--write-adr-index",
        dest="write_indexes",
        action="store_true",
        help=(
            "rewrite the ADR index and each docs/ kind index from their "
            "documents, then exit; --write-adr-index is its older name"
        ),
    )
    arguments = parser.parse_args(argv)

    tracked = tracked_markdown_files()
    readable = tracked + tracked_python_files()
    if arguments.paths:
        paths, unknown = select(readable, arguments.paths)
        for name in unknown:
            print(
                f"{name}: neither a tracked Markdown file nor tracked Python "
                "the link gate reads",
                file=sys.stderr,
            )
        if unknown:
            return 1
    else:
        paths = readable

    if arguments.write_indexes:
        unwritten = write_indexes(tracked)
        for problem in unwritten:
            print(problem.render(), file=sys.stderr)
        return 1 if unwritten else 0

    # The numbering, index and code map gates read the whole tree: a selection
    # can show neither a collision nor an omission from a file the caller did
    # not name.
    problems = (
        check_frontmatter(paths)
        + check_links(paths)
        + check_adr_numbers(tracked)
        + check_adr_index(tracked)
        + check_kind_indexes(tracked)
        + check_code_map(tracked_package_files())
    )
    for problem in sorted(
        problems, key=lambda item: (item.path, item.line, item.message)
    ):
        print(problem.render(), file=sys.stderr)
    if problems:
        print(f"\n{len(problems)} documentation problem(s).", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
